# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: BuildPublishTest
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build/Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --runtime win-x64 --self-contained false' 
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
       command: 'test'
       projects: '**/**Tests/*.csproj'
       arguments: '--configuration $(buildConfiguration)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy_to_WindowsDev 
  dependsOn: Build
  condition: |
    and
    (
      succeeded(),
      eq(variables['Build.SourceBranchName'], 'main')
    )
  jobs:
  - deployment: NETCoreApp_Dev
    environment:
      name: Windows-dev
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'

            - task: ExtractFiles@1
              inputs:
                archiveFilePatterns: 'C:\azagent\A1\_work\1\drop\s.zip'
                destinationFolder: 'C:\www'
                cleanDestinationFolder: false
                overwriteExistingFiles: true